import Head from 'next/head'
import Image from 'next/image'
import { Container, Row, Col } from '@nextui-org/react';

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    // <div className={styles.container}>
      <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
              Lorem ipsum dolor sit amet, consectetur adipisicing elit
          </p>
      </main>
      </Container>
    // </div>
  )
}
